[package]
name = "napi-example1"
version = "1.0.0"
authors = ["Alexey Orlenko <eaglexrlnk@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
napi = { version = "1.0.0", path = "../napi" }
